# Numpy Basic 
# Crated by Khairul E. Fahim
Date -27/06/2020

Numpy stands for numerical python. Numpy is a python library that is used for numerical computations. It is a core library for numerical and scientific computations. 

# Creating Single-dimensional Array

In [5]:
import numpy as np
lst1=[1,2,3,4]
np.array(lst1)

array([1, 2, 3, 4])

# Creating Multi-dimensional Array

In [7]:
n2=np.array([[1,2,3,4],[4,3,2,1]])
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [8]:
type(n2)

numpy.ndarray

# Initializing Numpy Array
An array can be filled with zeros using zeros function. Following example shows how we can fill a 2 rows and 3 column array with all zeros: 

In [10]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
type(n3)

numpy.ndarray

# Initializing Numpy Array with same number
Initializing Numpy array with same array can be done with the function named full. Let's say if we want to make a 2 into 2 numpy array filling all the rows and columns with the value 10

In [12]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

# Initializing Numpy Array within a range

In [14]:
n4=np.arange(10,20)
n4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Following example shows us how we can create a numpy within a range with a specific gap. Say for example we want a numpy array within a range 10 to 50 with a gap of 5. Gap is often called as increment as well

In [16]:
n5=np.arange(10,50,5)
n5

array([10, 15, 20, 25, 30, 35, 40, 45])

# Initializing Numpy array with random numbers 
Random numbers in an array can be initialized with the help of random submodule with randit method. Let's we want to generate 5 random numbers in the range 1 to 100 -

In [18]:
n6=np.random.randint(1,100,5)
n6

array([63, 67, 59, 37, 66])

# Checking the shape of numpy array

In [20]:
n6.shape

(5,)

using the shape function we can change the shape of an array. For example if we have a 2*4 matrix, using shape function we can convert it to a 4*2 matrix

In [23]:
n7=np.array([[1,2,3,4],[5,6,1,2]])
n7

array([[1, 2, 3, 4],
       [5, 6, 1, 2]])

In [25]:
n7.shape

(2, 4)

In [28]:
n7.shape=(4,2)
n7

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2]])

# Joining Numpy arrays
Joining numpy arrays can be done by vstack(),hstack(),column_stack()

# vstack() 
vstack is used when we want to one numpy array on top of the other. Example is shown below: 

In [31]:
n8=np.array([10,12,13])
n9=np.array([20,22,23])
np.vstack((n8,n9))

array([[10, 12, 13],
       [20, 22, 23]])

# hstack()
If we want stack horizontaly we can use hstack method. Example is shown below

In [36]:
n10=np.array([10,12,14,17])
n11=np.array([30,32,34,10])
np.hstack((n10,n11))

array([10, 12, 14, 17, 30, 32, 34, 10])

# column_stack()
If we want to store values in terms of columns, we can use column_stack()

In [37]:
np.column_stack((n10,n11))

array([[10, 30],
       [12, 32],
       [14, 34],
       [17, 10]])

# Numpy intersection method
To find out commmon values between two arrays we can used intersect1d method 

In [38]:
np.intersect1d(n10,n11)

array([10])

# setdiff1d()
To find out unique elements among different arrays, we use setdiff1d() method

In [39]:
np.setdiff1d(n10,n11)

array([12, 14, 17])

# Addition of Numpy arrays
Addition can be done using sum function

In [40]:
n12=np.array([10,20])
n13=np.array([30,40])
np.sum([n12,n13],axis=0) #here axis 0 means colums wise addition

array([40, 60])

In [41]:
np.sum([n12,n13],axis=1) #here axis 1 means row wise addition

array([30, 70])

# Numpy array mathematics


# Basic addition

In [42]:
n13+1

array([31, 41])

# Basic subtraction

In [43]:
n13-1

array([29, 39])

# Basic Multiplication

In [44]:
n13*2

array([60, 80])

# Basic Division

In [45]:
n13/2

array([15., 20.])

# Mean
In simple words we can think mean as average

In [46]:
n14=np.array([10,12,14,17,19,22])
n14.mean()

15.666666666666666

# Median
Median is the middle number

In [48]:
np.median(n14)

15.5

# Stand